[tool.ruff]
line-length = 100
exclude = [".tox",".git","*/migrations/*","*/static/CACHE/*"]


[isort]
line_length = 88
known_first_party = ["src","config"]
multi_line_output = 3
default_section = "THIRDPARTY"
skip = "venv/"
skip_glob = "**/migrations/*.py"
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[black]
max-line-length = 100
