# Generated by Django 4.2.1 on 2023-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="collection_requests")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
