# Generated by Django 4.2.1 on 2023-06-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("star_wars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionrequest",
            name="url",
        ),
        migrations.AlterField(
            model_name="collectionrequest",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="collection_requests"
            ),
        ),
    ]
