# Generated by Django 4.2.1 on 2023-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("star_wars", "0002_remove_collectionrequest_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeWorld",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homeworld_map", models.JSONField()),
            ],
        ),
    ]
